### ISSUE TITLE
Missing recipes & drops

### ISSUE THREAD

**Issue by Vincent0006** [CamoMano/Enriched#71]
### Bug Description

the recipe to make steel blend is missing. Unable to smelt steel blend into steel ingot. unable to craft steel ingots into steel blocks
the recipe to make Obsidian Alloy is missing. Unable to smelt the alloy into the ingot. unable to craft obsidian ingots into blocks
Tanzanite ore only drops sapphire.
Sapphire and Tanzanite blocks are unable to be crafted
unable to craft berry juice 
unable to craft beef stew

### Bug Reproduction Steps

tried it with and with out JEI and it still won't work

### Minecraft Log File

none

### Minecraft Crash Report

none

**Comment by CamoMano** [comment]
What version of the mod and Minecraft are you running?

**Comment by Vincent0006** [comment]
running 1.21
fabric version 0.15.11-.1.21

**Comment by Vincent0006** [comment]
I am also running version 4.0 of the mod (sorry for this late comment. I completely missed the first part of the question)
