### ISSUE TITLE
The marble steps have not dropped correctly

### ISSUE THREAD

**Issue by SanQianQVQ** [CamoMano/Enriched#80]
### Enriched Version

3.0.1

### Fabric API Version

0.92.2

### Fabric Loader Version

0.15.x

### Bug Description

When the two marble steps are put together up and down, and then use the pickaxe to dig, the square seems to be considered one rather than two, which will only drop one marble step.

### Bug Reproduction Steps

1. Place two marble steps in one
2. dig
3. drop, but only one

### Minecraft Log File

unnecessary

### Minecraft Crash Report

unnecessary

**Comment by SanQianQVQ** [comment]
![1](https://github.com/user-attachments/assets/f8c5cd9a-11d7-4eb0-bd4e-b62e24c08010)
![2](https://github.com/user-attachments/assets/3e475a3a-8d8b-4595-8391-cc3d6a1b3085)

**Comment by SanQianQVQ** [comment]
In addition, using Minecraft 1.20.1

**Comment by CamoMano** [comment]
This should be an easy fix. I'll take a look sometime this week/weekend.

**Comment by CamoMano** [comment]
Give this a try

[enriched-3.0.1-test.zip](https://github.com/user-attachments/files/16918839/enriched-3.0.1-test.zip)
